// AUTO-GENERATED by scripts/generate.mjs from spec/swagger.json. Do not edit.
export interface ToolDef {
  name: string;
  description: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  pathParams: { arg: string; name: string }[];
  queryParams: { arg: string; name: string }[];
  hasBody: boolean;
  inputSchema: Record<string, unknown>;
  annotations: Record<string, unknown>;
}

export const TOOLS: ToolDef[] = [
  {
    "name": "accounts_get_accounts",
    "description": "Retrieves all accounts\n[GET /api/accounts]",
    "method": "GET",
    "path": "/api/accounts",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      },
      {
        "arg": "include",
        "name": "include"
      },
      {
        "arg": "filter",
        "name": "$filter"
      },
      {
        "arg": "orderBy",
        "name": "$orderBy"
      },
      {
        "arg": "minBillingAddressUpdatedAt",
        "name": "minBillingAddressUpdatedAt"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        },
        "include": {
          "type": "string"
        },
        "filter": {
          "type": "string",
          "description": "A function that must evaluate to true for an account to be returned. (OData-style expression passed as $filter)"
        },
        "orderBy": {
          "type": "string",
          "description": "Determines which values are used to sort a collection of accounts. (OData-style expression passed as $orderBy)"
        },
        "minBillingAddressUpdatedAt": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "annotations": {
      "title": "Retrieves all accounts",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "accounts_create_account",
    "description": "Creates an account\n[POST /api/accounts] WRITE.",
    "method": "POST",
    "path": "/api/accounts",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true,
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "The account's name",
              "minLength": 1
            },
            "phone": {
              "type": "string"
            },
            "email": {
              "type": "string",
              "format": "email"
            },
            "billingAddress": {
              "type": "object",
              "properties": {
                "address": {
                  "type": "string",
                  "description": "Billing address name"
                },
                "address2": {
                  "type": "string",
                  "description": "Billing address secondary name"
                },
                "city": {
                  "type": "string",
                  "description": "Billing address city"
                },
                "postCode": {
                  "type": "string",
                  "description": "Billing address post code"
                },
                "countryId": {
                  "type": "integer",
                  "description": "Address country ID"
                },
                "stateId": {
                  "type": "integer",
                  "description": "Address state ID"
                }
              },
              "required": [
                "countryId"
              ]
            },
            "customFields": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer",
                    "description": "The custom field ID."
                  },
                  "value": {
                    "type": "string",
                    "description": "The custom field value."
                  }
                },
                "required": [
                  "id"
                ]
              }
            }
          },
          "required": [
            "name",
            "orderingEnabled",
            "separateInvoices",
            "taxable",
            "creditLimit",
            "autoInvoiceNotification",
            "noteType",
            "resellingEnabled",
            "isAffiliate",
            "isBillingFrequencyEnabled",
            "billingFrequencyMarkup"
          ],
          "description": "This request contains all the fields needed to create an account."
        }
      },
      "required": [
        "body"
      ]
    },
    "annotations": {
      "title": "Creates an account",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "name": "accounts_get_account",
    "description": "Retrieves a single account that corresponds to an account ID\n[GET /api/accounts/{accountId}]",
    "method": "GET",
    "path": "/api/accounts/{accountId}",
    "pathParams": [
      {
        "arg": "accountId",
        "name": "accountId"
      }
    ],
    "queryParams": [
      {
        "arg": "include",
        "name": "include"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "accountId": {
          "type": "integer",
          "description": "The account ID."
        },
        "include": {
          "type": "string"
        }
      },
      "required": [
        "accountId"
      ]
    },
    "annotations": {
      "title": "Retrieves a single account that corresponds to an account ID",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "accounts_patch_account",
    "description": "Updates an account\n[PATCH /api/accounts/{accountId}] WRITE.",
    "method": "PATCH",
    "path": "/api/accounts/{accountId}",
    "pathParams": [
      {
        "arg": "accountId",
        "name": "accountId"
      }
    ],
    "queryParams": [],
    "hasBody": true,
    "inputSchema": {
      "type": "object",
      "properties": {
        "accountId": {
          "type": "integer",
          "description": "The account ID."
        },
        "body": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": true
          },
          "description": "The patch document upon with which updating operations will be performed."
        }
      },
      "required": [
        "accountId",
        "body"
      ]
    },
    "annotations": {
      "title": "Updates an account",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "name": "accounts_get_account_billing_address",
    "description": "Retrieves the billing address that corresponds to an account ID\n[GET /api/accounts/{accountId}/billingaddress]",
    "method": "GET",
    "path": "/api/accounts/{accountId}/billingaddress",
    "pathParams": [
      {
        "arg": "accountId",
        "name": "accountId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "accountId": {
          "type": "integer",
          "description": "The account ID."
        }
      },
      "required": [
        "accountId"
      ]
    },
    "annotations": {
      "title": "Retrieves the billing address that corresponds to an account ID",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "accounts_get",
    "description": "Retrieves the custom fields that correspond to an account ID\n[GET /api/accounts/{accountId}/customfields]",
    "method": "GET",
    "path": "/api/accounts/{accountId}/customfields",
    "pathParams": [
      {
        "arg": "accountId",
        "name": "accountId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "accountId": {
          "type": "integer",
          "description": "The account ID."
        }
      },
      "required": [
        "accountId"
      ]
    },
    "annotations": {
      "title": "Retrieves the custom fields that correspond to an account ID",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "accounts_put",
    "description": "Updates the custom fields of a specific account based on the given ID.\n[PUT /api/accounts/{accountId}/customfields] WRITE.",
    "method": "PUT",
    "path": "/api/accounts/{accountId}/customfields",
    "pathParams": [
      {
        "arg": "accountId",
        "name": "accountId"
      }
    ],
    "queryParams": [],
    "hasBody": true,
    "inputSchema": {
      "type": "object",
      "properties": {
        "accountId": {
          "type": "integer",
          "description": "The account ID."
        },
        "body": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "description": "The custom field ID."
              },
              "value": {
                "type": "string",
                "description": "The custom field value."
              }
            },
            "required": [
              "id"
            ]
          },
          "description": "Contains the custom fields values."
        }
      },
      "required": [
        "accountId",
        "body"
      ]
    },
    "annotations": {
      "title": "Updates the custom fields of a specific account based on the given ID.",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "accounts_get_account_sync_options",
    "description": "Retrieves the synchronization options of a specific account based on the given ID.\nSupports the retrieval of the options for a specific provision system based on the given ID.\n[GET /api/accounts/{accountId}/syncoptions/{systemId}]",
    "method": "GET",
    "path": "/api/accounts/{accountId}/syncoptions/{systemId}",
    "pathParams": [
      {
        "arg": "accountId",
        "name": "accountId"
      },
      {
        "arg": "systemId",
        "name": "systemId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "accountId": {
          "type": "integer",
          "description": "The account ID."
        },
        "systemId": {
          "type": "integer",
          "description": "[Optional] The provisioning system ID."
        }
      },
      "required": [
        "accountId",
        "systemId"
      ]
    },
    "annotations": {
      "title": "Retrieves the synchronization options of a specific account based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "accounts_save_account_sync_options",
    "description": "Updates account's sync options.\nThis API call updates sync options for a provisioning system.\n[POST /api/accounts/{accountId}/syncoptions/{systemId}] WRITE.",
    "method": "POST",
    "path": "/api/accounts/{accountId}/syncoptions/{systemId}",
    "pathParams": [
      {
        "arg": "accountId",
        "name": "accountId"
      },
      {
        "arg": "systemId",
        "name": "systemId"
      }
    ],
    "queryParams": [],
    "hasBody": true,
    "inputSchema": {
      "type": "object",
      "properties": {
        "accountId": {
          "type": "integer",
          "description": "The ID of the Account."
        },
        "systemId": {
          "type": "integer",
          "description": "The provisioning system ID."
        },
        "body": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "value": {
                "type": "string"
              },
              "alias": {
                "type": "string"
              }
            }
          },
          "description": "Sync Options."
        }
      },
      "required": [
        "accountId",
        "systemId",
        "body"
      ]
    },
    "annotations": {
      "title": "Updates account's sync options.",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "name": "accounts_synchronize_account",
    "description": "Synchronize account with external system\n[POST /api/accounts/{accountId}/synchronizations/{systemId}] WRITE.",
    "method": "POST",
    "path": "/api/accounts/{accountId}/synchronizations/{systemId}",
    "pathParams": [
      {
        "arg": "accountId",
        "name": "accountId"
      },
      {
        "arg": "systemId",
        "name": "systemId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "accountId": {
          "type": "integer",
          "description": "The account ID."
        },
        "systemId": {
          "type": "integer",
          "description": "The ID of the external system"
        }
      },
      "required": [
        "accountId",
        "systemId"
      ]
    },
    "annotations": {
      "title": "Synchronize account with external system",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "name": "assets_get_assets",
    "description": "Retrieves the assets of the organization.\n[GET /api/assets]",
    "method": "GET",
    "path": "/api/assets",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      },
      {
        "arg": "include",
        "name": "include"
      },
      {
        "arg": "filter",
        "name": "$filter"
      },
      {
        "arg": "orderBy",
        "name": "$orderBy"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        },
        "include": {
          "type": "string"
        },
        "filter": {
          "type": "string",
          "description": "A function that must evaluate to true for an asset to be returned. (OData-style expression passed as $filter)"
        },
        "orderBy": {
          "type": "string",
          "description": "Determines what values are used to order a collection of assets (OData-style expression passed as $orderBy)"
        }
      }
    },
    "annotations": {
      "title": "Retrieves the assets of the organization.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "assets_get_asset",
    "description": "Retrieves a specific asset based on the given ID.\n[GET /api/assets/{assetId}]",
    "method": "GET",
    "path": "/api/assets/{assetId}",
    "pathParams": [
      {
        "arg": "assetId",
        "name": "assetId"
      }
    ],
    "queryParams": [
      {
        "arg": "include",
        "name": "include"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "assetId": {
          "type": "string",
          "description": "The asset ID.",
          "format": "uuid"
        },
        "include": {
          "type": "string"
        }
      },
      "required": [
        "assetId"
      ]
    },
    "annotations": {
      "title": "Retrieves a specific asset based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "invoices_get_invoices",
    "description": "Retrieves all invoices\n[GET /api/invoices]",
    "method": "GET",
    "path": "/api/invoices",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "filter",
        "name": "$filter"
      },
      {
        "arg": "orderBy",
        "name": "$orderBy"
      },
      {
        "arg": "include",
        "name": "include"
      },
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      },
      {
        "arg": "transactionCurrency",
        "name": "transactionCurrency"
      },
      {
        "arg": "skipRounding",
        "name": "skipRounding"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "filter": {
          "type": "string",
          "description": "A function that must evaluate to true for an invoice to be returned. (OData-style expression passed as $filter)"
        },
        "orderBy": {
          "type": "string",
          "description": "Determines what values are used to order a collection of invoices. (OData-style expression passed as $orderBy)"
        },
        "include": {
          "type": "string",
          "description": "The include parameter is used to include extra information about the invoice.\nThe values that are supported right now are customFields, items and analysisItems."
        },
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        },
        "transactionCurrency": {
          "type": "boolean",
          "description": "Given as 'true' when the user wants the invoice totals in the transaction currency.",
          "default": false
        },
        "skipRounding": {
          "type": "boolean",
          "description": "Given as 'true' when the user wants specific values without rounding.",
          "default": false
        }
      }
    },
    "annotations": {
      "title": "Retrieves all invoices",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "invoices_get_invoice",
    "description": "Retrieves a specific invoice based on the given ID\n[GET /api/invoices/{invoiceId}]",
    "method": "GET",
    "path": "/api/invoices/{invoiceId}",
    "pathParams": [
      {
        "arg": "invoiceId",
        "name": "invoiceId"
      }
    ],
    "queryParams": [
      {
        "arg": "include",
        "name": "include"
      },
      {
        "arg": "transactionCurrency",
        "name": "transactionCurrency"
      },
      {
        "arg": "skipRounding",
        "name": "skipRounding"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "invoiceId": {
          "type": "string",
          "description": "The ID of the invoice.",
          "format": "uuid"
        },
        "include": {
          "type": "string",
          "description": "The include parameter is used to include extra information about the invoice.\nThe values that are supported right now are customFields, items and analysisItems."
        },
        "transactionCurrency": {
          "type": "boolean",
          "description": "Given as 'true' when the user wants the invoice totals in the transaction currency.",
          "default": false
        },
        "skipRounding": {
          "type": "boolean",
          "description": "Given as 'true' when the user wants specific values without rounding.",
          "default": false
        }
      },
      "required": [
        "invoiceId"
      ]
    },
    "annotations": {
      "title": "Retrieves a specific invoice based on the given ID",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "invoices_get_invoice_items",
    "description": "Retrieves the items of a specific invoice based on the given ID\n[GET /api/invoices/{invoiceId}/items]",
    "method": "GET",
    "path": "/api/invoices/{invoiceId}/items",
    "pathParams": [
      {
        "arg": "invoiceId",
        "name": "invoiceId"
      }
    ],
    "queryParams": [
      {
        "arg": "analysis",
        "name": "analysis"
      },
      {
        "arg": "transactionCurrency",
        "name": "transactionCurrency"
      },
      {
        "arg": "skipRounding",
        "name": "skipRounding"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "invoiceId": {
          "type": "string",
          "description": "The invoice ID.",
          "format": "uuid"
        },
        "analysis": {
          "type": "boolean",
          "description": "Given as 'true' when user wants all the items in an analytical pattern.",
          "default": false
        },
        "transactionCurrency": {
          "type": "boolean",
          "description": "Given as 'true' when user wants the totals of all items in the transactionCurrency.",
          "default": false
        },
        "skipRounding": {
          "type": "boolean",
          "description": "Given as 'true' when the user wants specific values without rounding.",
          "default": false
        }
      },
      "required": [
        "invoiceId"
      ]
    },
    "annotations": {
      "title": "Retrieves the items of a specific invoice based on the given ID",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "invoices_get",
    "description": "Retrieves the custom fields of an existing invoice based on the given ID\n[GET /api/invoices/{invoiceId}/customfields]",
    "method": "GET",
    "path": "/api/invoices/{invoiceId}/customfields",
    "pathParams": [
      {
        "arg": "invoiceId",
        "name": "invoiceId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "invoiceId": {
          "type": "string",
          "description": "The Invoice ID.",
          "format": "uuid"
        }
      },
      "required": [
        "invoiceId"
      ]
    },
    "annotations": {
      "title": "Retrieves the custom fields of an existing invoice based on the given ID",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "invoices_get_invoice_orders",
    "description": "Retrieves the related orders of an invoice based on the given ID\n[GET /api/invoices/{invoiceId}/orders]",
    "method": "GET",
    "path": "/api/invoices/{invoiceId}/orders",
    "pathParams": [
      {
        "arg": "invoiceId",
        "name": "invoiceId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "invoiceId": {
          "type": "string",
          "description": "The invoice ID.",
          "format": "uuid"
        }
      },
      "required": [
        "invoiceId"
      ]
    },
    "annotations": {
      "title": "Retrieves the related orders of an invoice based on the given ID",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_get_orders",
    "description": "Retrieves the orders of the organization.\n[GET /api/orders]",
    "method": "GET",
    "path": "/api/orders",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      },
      {
        "arg": "include",
        "name": "include"
      },
      {
        "arg": "stage",
        "name": "stage"
      },
      {
        "arg": "filter",
        "name": "$filter"
      },
      {
        "arg": "orderBy",
        "name": "$orderBy"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        },
        "include": {
          "type": "string"
        },
        "stage": {
          "type": "string",
          "description": "A parameter to retrieve Confirmed, Draft or All orders.",
          "default": "Confirmed"
        },
        "filter": {
          "type": "string",
          "description": "A function that must evaluate to true for an order to be returned. (OData-style expression passed as $filter)"
        },
        "orderBy": {
          "type": "string",
          "description": "Determines what values are used to order a collection of orders. (OData-style expression passed as $orderBy)"
        }
      }
    },
    "annotations": {
      "title": "Retrieves the orders of the organization.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_post",
    "description": "Creates a new order for the organization.\n[POST /api/orders] WRITE.",
    "method": "POST",
    "path": "/api/orders",
    "pathParams": [],
    "queryParams": [],
    "hasBody": true,
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "object",
          "properties": {
            "accountId": {
              "type": "integer",
              "minimum": 1,
              "maximum": 2147483647
            },
            "customFields": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer",
                    "description": "The custom field ID."
                  },
                  "value": {
                    "type": "string",
                    "description": "The custom field value."
                  }
                },
                "required": [
                  "id"
                ]
              }
            }
          },
          "required": [
            "accountId"
          ],
          "description": "Contains the information of the new order."
        }
      },
      "required": [
        "body"
      ]
    },
    "annotations": {
      "title": "Creates a new order for the organization.",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_get_order",
    "description": "Retrieves a specific order based on the given ID.\n[GET /api/orders/{orderId}]",
    "method": "GET",
    "path": "/api/orders/{orderId}",
    "pathParams": [
      {
        "arg": "orderId",
        "name": "orderId"
      }
    ],
    "queryParams": [
      {
        "arg": "include",
        "name": "include"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "orderId": {
          "type": "string",
          "description": "The order ID.",
          "format": "uuid"
        },
        "include": {
          "type": "string"
        }
      },
      "required": [
        "orderId"
      ]
    },
    "annotations": {
      "title": "Retrieves a specific order based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_checkout",
    "description": "Sends a request for a specific order to be executed.\n[POST /api/orders/{orderId}/checkout] WRITE.",
    "method": "POST",
    "path": "/api/orders/{orderId}/checkout",
    "pathParams": [
      {
        "arg": "orderId",
        "name": "orderId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "orderId": {
          "type": "string",
          "description": "The order ID.",
          "format": "uuid"
        }
      },
      "required": [
        "orderId"
      ]
    },
    "annotations": {
      "title": "Sends a request for a specific order to be executed.",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_get_execution_status",
    "description": "Retrieves the execution status of a specific order.\n[GET /api/orders/{orderId}/execute/status]",
    "method": "GET",
    "path": "/api/orders/{orderId}/execute/status",
    "pathParams": [
      {
        "arg": "orderId",
        "name": "orderId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "orderId": {
          "type": "string",
          "description": "The order ID.",
          "format": "uuid"
        }
      },
      "required": [
        "orderId"
      ]
    },
    "annotations": {
      "title": "Retrieves the execution status of a specific order.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_get_order_items",
    "description": "Retrieves the items of a specific order based on the given ID.\n[GET /api/orders/{orderId}/items]",
    "method": "GET",
    "path": "/api/orders/{orderId}/items",
    "pathParams": [
      {
        "arg": "orderId",
        "name": "orderId"
      }
    ],
    "queryParams": [
      {
        "arg": "include",
        "name": "include"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "orderId": {
          "type": "string",
          "description": "The order ID.",
          "format": "uuid"
        },
        "include": {
          "type": "string"
        }
      },
      "required": [
        "orderId"
      ]
    },
    "annotations": {
      "title": "Retrieves the items of a specific order based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_create_order_item",
    "description": "Creates an order item for an existing order of the current organization based on the given ID.\n[POST /api/orders/{orderId}/items] WRITE.",
    "method": "POST",
    "path": "/api/orders/{orderId}/items",
    "pathParams": [
      {
        "arg": "orderId",
        "name": "orderId"
      }
    ],
    "queryParams": [],
    "hasBody": true,
    "inputSchema": {
      "type": "object",
      "properties": {
        "orderId": {
          "type": "string",
          "description": "The order ID.",
          "format": "uuid"
        },
        "body": {
          "type": "object",
          "properties": {
            "productId": {
              "type": "string",
              "format": "uuid"
            },
            "unitId": {
              "type": "string",
              "format": "uuid"
            },
            "quantity": {
              "type": "number"
            },
            "customEndDate": {
              "type": "string",
              "format": "date-time"
            },
            "relatedSubscriptionId": {
              "type": "string",
              "format": "uuid"
            },
            "relatedAddonItemId": {
              "type": "string",
              "format": "uuid"
            },
            "relatedItemId": {
              "type": "string",
              "format": "uuid"
            },
            "billingFrequencyOptionId": {
              "type": "string",
              "format": "uuid"
            },
            "characteristics": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "The characteristic 's ID.",
                    "format": "uuid",
                    "minLength": 1
                  },
                  "value": {
                    "type": "string",
                    "description": "The characteristic 's value."
                  }
                },
                "required": [
                  "id"
                ]
              }
            }
          },
          "description": "Contains the item information."
        }
      },
      "required": [
        "orderId",
        "body"
      ]
    },
    "annotations": {
      "title": "Creates an order item for an existing order of the current organization based on the given ID.",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_get_orderitem",
    "description": "Retrieves a specific item of a specific order based on the given IDs.\n[GET /api/orders/{orderId}/items/{itemId}]",
    "method": "GET",
    "path": "/api/orders/{orderId}/items/{itemId}",
    "pathParams": [
      {
        "arg": "orderId",
        "name": "orderId"
      },
      {
        "arg": "itemId",
        "name": "itemId"
      }
    ],
    "queryParams": [
      {
        "arg": "include",
        "name": "include"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "orderId": {
          "type": "string",
          "description": "The order ID.",
          "format": "uuid"
        },
        "itemId": {
          "type": "string",
          "description": "The item ID.",
          "format": "uuid"
        },
        "include": {
          "type": "string"
        }
      },
      "required": [
        "orderId",
        "itemId"
      ]
    },
    "annotations": {
      "title": "Retrieves a specific item of a specific order based on the given IDs.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_delete",
    "description": "Deletes an existing item of an existing order of the current organization based on the given IDs.\n[DELETE /api/orders/{orderId}/items/{itemId}] WRITE (destructive).",
    "method": "DELETE",
    "path": "/api/orders/{orderId}/items/{itemId}",
    "pathParams": [
      {
        "arg": "orderId",
        "name": "orderId"
      },
      {
        "arg": "itemId",
        "name": "itemId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "orderId": {
          "type": "string",
          "description": "The order ID.",
          "format": "uuid"
        },
        "itemId": {
          "type": "string",
          "description": "The item ID.",
          "format": "uuid"
        }
      },
      "required": [
        "orderId",
        "itemId"
      ]
    },
    "annotations": {
      "title": "Deletes an existing item of an existing order of the current organization based on the given IDs.",
      "readOnlyHint": false,
      "destructiveHint": true,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_get_characteristics",
    "description": "Retrieves the order characteristics of a specific item of a specific order based on the given IDs.\n[GET /api/orders/{orderId}/items/{itemId}/characteristics]",
    "method": "GET",
    "path": "/api/orders/{orderId}/items/{itemId}/characteristics",
    "pathParams": [
      {
        "arg": "orderId",
        "name": "orderId"
      },
      {
        "arg": "itemId",
        "name": "itemId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "orderId": {
          "type": "string",
          "description": "The order ID.",
          "format": "uuid"
        },
        "itemId": {
          "type": "string",
          "description": "The item ID.",
          "format": "uuid"
        }
      },
      "required": [
        "orderId",
        "itemId"
      ]
    },
    "annotations": {
      "title": "Retrieves the order characteristics of a specific item of a specific order based on the given IDs.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_update_characteristics",
    "description": "Updates the characteristics of an existing item of an existing order based on the given IDs.\n[PUT /api/orders/{orderId}/items/{itemId}/characteristics] WRITE.",
    "method": "PUT",
    "path": "/api/orders/{orderId}/items/{itemId}/characteristics",
    "pathParams": [
      {
        "arg": "orderId",
        "name": "orderId"
      },
      {
        "arg": "itemId",
        "name": "itemId"
      }
    ],
    "queryParams": [],
    "hasBody": true,
    "inputSchema": {
      "type": "object",
      "properties": {
        "orderId": {
          "type": "string",
          "description": "The order ID.",
          "format": "uuid"
        },
        "itemId": {
          "type": "string",
          "description": "The item ID.",
          "format": "uuid"
        },
        "body": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "description": "The characteristic 's ID.",
                "format": "uuid",
                "minLength": 1
              },
              "value": {
                "type": "string",
                "description": "The characteristic 's value."
              }
            },
            "required": [
              "id"
            ]
          },
          "description": "Contains the updated characteristics of the item."
        }
      },
      "required": [
        "orderId",
        "itemId",
        "body"
      ]
    },
    "annotations": {
      "title": "Updates the characteristics of an existing item of an existing order based on the given IDs.",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_get",
    "description": "Retrieves the custom fields of a specific order based on the given ID.\n[GET /api/orders/{orderId}/customfields]",
    "method": "GET",
    "path": "/api/orders/{orderId}/customfields",
    "pathParams": [
      {
        "arg": "orderId",
        "name": "orderId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "orderId": {
          "type": "string",
          "description": "The order ID.",
          "format": "uuid"
        }
      },
      "required": [
        "orderId"
      ]
    },
    "annotations": {
      "title": "Retrieves the custom fields of a specific order based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "orders_put",
    "description": "Updates the values of the custom fields of an existing order of the current organization based on the given ID.\n[PUT /api/orders/{orderId}/customfields] WRITE.",
    "method": "PUT",
    "path": "/api/orders/{orderId}/customfields",
    "pathParams": [
      {
        "arg": "orderId",
        "name": "orderId"
      }
    ],
    "queryParams": [],
    "hasBody": true,
    "inputSchema": {
      "type": "object",
      "properties": {
        "orderId": {
          "type": "string",
          "format": "uuid"
        },
        "body": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "description": "The custom field ID."
              },
              "value": {
                "type": "string",
                "description": "The custom field value."
              }
            },
            "required": [
              "id"
            ]
          }
        }
      },
      "required": [
        "orderId",
        "body"
      ]
    },
    "annotations": {
      "title": "Updates the values of the custom fields of an existing order of the current organization based on the given ID.",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "organization_get_countries",
    "description": "Retrieves the countries of the current organization.\n[GET /api/organization/countries]",
    "method": "GET",
    "path": "/api/organization/countries",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "filter",
        "name": "$filter"
      },
      {
        "arg": "orderby",
        "name": "$orderby"
      },
      {
        "arg": "include",
        "name": "include"
      },
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "filter": {
          "type": "string",
          "description": "A function that must evaluate to true for a country to be returned. (OData-style expression passed as $filter)"
        },
        "orderby": {
          "type": "string",
          "description": "Determines what values are used to order a collection of countries. (OData-style expression passed as $orderby)"
        },
        "include": {
          "type": "string",
          "description": "The include parameter is used to include extra information about the country.\nThe supported value is 'states'."
        },
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        }
      }
    },
    "annotations": {
      "title": "Retrieves the countries of the current organization.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "organization_get_setup_account_custom_fields",
    "description": "Retrieves the account custom fields of the current organization.\n[GET /api/organization/accounts/customfields]",
    "method": "GET",
    "path": "/api/organization/accounts/customfields",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "filter",
        "name": "$filter"
      },
      {
        "arg": "orderby",
        "name": "$orderby"
      },
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "filter": {
          "type": "string",
          "description": "A function that must evaluate to true for an account custom field to be returned. (OData-style expression passed as $filter)"
        },
        "orderby": {
          "type": "string",
          "description": "Determines what values are used to order a collection of account custom fields. (OData-style expression passed as $orderby)"
        },
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        }
      }
    },
    "annotations": {
      "title": "Retrieves the account custom fields of the current organization.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "organization_get_setup_invoice_custom_fields",
    "description": "Retrieves the invoice custom fields of the current organization.\n[GET /api/organization/invoices/customfields]",
    "method": "GET",
    "path": "/api/organization/invoices/customfields",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "filter",
        "name": "$filter"
      },
      {
        "arg": "orderby",
        "name": "$orderby"
      },
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "filter": {
          "type": "string",
          "description": "A function that must evaluate to true for an invoice custom field to be returned. (OData-style expression passed as $filter)"
        },
        "orderby": {
          "type": "string",
          "description": "Determines what values are used to order a collection of invoice custom fields. (OData-style expression passed as $orderby)"
        },
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        }
      }
    },
    "annotations": {
      "title": "Retrieves the invoice custom fields of the current organization.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "organization_get_unit_groups",
    "description": "Retrieves the unit groups of the current organization.\n[GET /api/organization/unitGroups]",
    "method": "GET",
    "path": "/api/organization/unitGroups",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "filter",
        "name": "$filter"
      },
      {
        "arg": "orderby",
        "name": "$orderby"
      },
      {
        "arg": "include",
        "name": "include"
      },
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "filter": {
          "type": "string",
          "description": "A function that must evaluate to true for a unit group to be returned. (OData-style expression passed as $filter)"
        },
        "orderby": {
          "type": "string",
          "description": "Determines what values are used to order a collection of unit groups. (OData-style expression passed as $orderby)"
        },
        "include": {
          "type": "string",
          "description": "The include parameter is used to include extra information about the unit groups.\nThe supported value is 'units'."
        },
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        }
      }
    },
    "annotations": {
      "title": "Retrieves the unit groups of the current organization.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "organization_get_setup_product_custom_fields",
    "description": "Retrieves the product custom fields of the current organization.\n[GET /api/organization/products/customfields]",
    "method": "GET",
    "path": "/api/organization/products/customfields",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "filter",
        "name": "$filter"
      },
      {
        "arg": "orderby",
        "name": "$orderby"
      },
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "filter": {
          "type": "string",
          "description": "A function that must evaluate to true for a product custom field to be returned. (OData-style expression passed as $filter)"
        },
        "orderby": {
          "type": "string",
          "description": "Determines what values are used to order a collection of product custom fields. (OData-style expression passed as $orderby)"
        },
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        }
      }
    },
    "annotations": {
      "title": "Retrieves the product custom fields of the current organization.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "organization_get_external_systems",
    "description": "Retrieves the external systems of the current organization.\n[GET /api/organization/externalSystems]",
    "method": "GET",
    "path": "/api/organization/externalSystems",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        }
      }
    },
    "annotations": {
      "title": "Retrieves the external systems of the current organization.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "organization_country_states_get_country_states",
    "description": "Retrieves the states of a specfic country of the current organization based on the given ID.\n[GET /api/organization/countries/{countryId}/states]",
    "method": "GET",
    "path": "/api/organization/countries/{countryId}/states",
    "pathParams": [
      {
        "arg": "countryId",
        "name": "countryId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "countryId": {
          "type": "integer",
          "description": "The country ID."
        }
      },
      "required": [
        "countryId"
      ]
    },
    "annotations": {
      "title": "Retrieves the states of a specfic country of the current organization based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "product_addons_get_product_addons",
    "description": "Retrieves the addons of a specific product based on the given ID.\n[GET /api/products/{productId}/addons]",
    "method": "GET",
    "path": "/api/products/{productId}/addons",
    "pathParams": [
      {
        "arg": "productId",
        "name": "productId"
      }
    ],
    "queryParams": [
      {
        "arg": "include",
        "name": "include"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "productId": {
          "type": "string",
          "description": "The product ID.",
          "format": "uuid"
        },
        "include": {
          "type": "string"
        }
      },
      "required": [
        "productId"
      ]
    },
    "annotations": {
      "title": "Retrieves the addons of a specific product based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "products_get_products",
    "description": "Retrieves the products of the current organization.\n[GET /api/products]",
    "method": "GET",
    "path": "/api/products",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      },
      {
        "arg": "include",
        "name": "include"
      },
      {
        "arg": "filter",
        "name": "$filter"
      },
      {
        "arg": "orderBy",
        "name": "$orderBy"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        },
        "include": {
          "type": "string"
        },
        "filter": {
          "type": "string",
          "description": "A function that must evaluate to true for a product to be returned (OData-style expression passed as $filter)"
        },
        "orderBy": {
          "type": "string",
          "description": "Determines what values are used to order a collection of products (OData-style expression passed as $orderBy)"
        }
      }
    },
    "annotations": {
      "title": "Retrieves the products of the current organization.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "products_get_product",
    "description": "Retrieves a specific product of the current organization based on the given ID.\n[GET /api/products/{productId}]",
    "method": "GET",
    "path": "/api/products/{productId}",
    "pathParams": [
      {
        "arg": "productId",
        "name": "productId"
      }
    ],
    "queryParams": [
      {
        "arg": "include",
        "name": "include"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "productId": {
          "type": "string",
          "description": "The product ID.",
          "format": "uuid"
        },
        "include": {
          "type": "string"
        }
      },
      "required": [
        "productId"
      ]
    },
    "annotations": {
      "title": "Retrieves a specific product of the current organization based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "products_get_product_billing_frequency_options",
    "description": "Retrieves a specific product's billing frequency options.\n[GET /api/products/{productId}/billingfrequencyoptions]",
    "method": "GET",
    "path": "/api/products/{productId}/billingfrequencyoptions",
    "pathParams": [
      {
        "arg": "productId",
        "name": "productId"
      }
    ],
    "queryParams": [
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "productId": {
          "type": "string",
          "description": "The product ID.",
          "format": "uuid"
        },
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        }
      },
      "required": [
        "productId"
      ]
    },
    "annotations": {
      "title": "Retrieves a specific product's billing frequency options.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "products_get_product_pricing",
    "description": "Retrieves the pricing information of a specific product based on the given ID.\n[GET /api/products/{productId}/pricing]",
    "method": "GET",
    "path": "/api/products/{productId}/pricing",
    "pathParams": [
      {
        "arg": "productId",
        "name": "productId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "productId": {
          "type": "string",
          "description": "The product ID.",
          "format": "uuid"
        }
      },
      "required": [
        "productId"
      ]
    },
    "annotations": {
      "title": "Retrieves the pricing information of a specific product based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "products_get_product_external_pricing",
    "description": "Retrieves the pricing information of a specific product based on the given ID.\n[GET /api/products/{productId}/externalprices]",
    "method": "GET",
    "path": "/api/products/{productId}/externalprices",
    "pathParams": [
      {
        "arg": "productId",
        "name": "productId"
      }
    ],
    "queryParams": [
      {
        "arg": "unitId",
        "name": "unitId"
      },
      {
        "arg": "currency",
        "name": "currency"
      },
      {
        "arg": "accountId",
        "name": "accountId"
      },
      {
        "arg": "countryId",
        "name": "countryId"
      },
      {
        "arg": "billingFrequencyOptionId",
        "name": "billingFrequencyOptionId"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "productId": {
          "type": "string",
          "description": "The product ID.",
          "format": "uuid"
        },
        "unitId": {
          "type": "string",
          "format": "uuid"
        },
        "currency": {
          "type": "string",
          "minLength": 1
        },
        "accountId": {
          "type": "integer"
        },
        "countryId": {
          "type": "integer"
        },
        "billingFrequencyOptionId": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "productId",
        "unitId",
        "currency"
      ]
    },
    "annotations": {
      "title": "Retrieves the pricing information of a specific product based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "products_get_product_characteristics",
    "description": "Retrieves the characteristics of a specific product based on the given ID.\n[GET /api/products/{productId}/characteristics]",
    "method": "GET",
    "path": "/api/products/{productId}/characteristics",
    "pathParams": [
      {
        "arg": "productId",
        "name": "productId"
      }
    ],
    "queryParams": [
      {
        "arg": "include",
        "name": "include"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "productId": {
          "type": "string",
          "description": "The product ID.",
          "format": "uuid"
        },
        "include": {
          "type": "string"
        }
      },
      "required": [
        "productId"
      ]
    },
    "annotations": {
      "title": "Retrieves the characteristics of a specific product based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "products_get_custom_fields",
    "description": "Retrieves the custom fields of a specific product based on the given ID.\n[GET /api/products/{productId}/customfields]",
    "method": "GET",
    "path": "/api/products/{productId}/customfields",
    "pathParams": [
      {
        "arg": "productId",
        "name": "productId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "productId": {
          "type": "string",
          "description": "The product ID.",
          "format": "uuid"
        }
      },
      "required": [
        "productId"
      ]
    },
    "annotations": {
      "title": "Retrieves the custom fields of a specific product based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "subscriptions_get_subscriptions",
    "description": "Retrieves the subscriptions.\n[GET /api/subscriptions]",
    "method": "GET",
    "path": "/api/subscriptions",
    "pathParams": [],
    "queryParams": [
      {
        "arg": "pageIndex",
        "name": "pageIndex"
      },
      {
        "arg": "pageSize",
        "name": "pageSize"
      },
      {
        "arg": "include",
        "name": "include"
      },
      {
        "arg": "filter",
        "name": "$filter"
      },
      {
        "arg": "orderBy",
        "name": "$orderBy"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "pageIndex": {
          "type": "integer",
          "default": 1
        },
        "pageSize": {
          "type": "integer",
          "default": 10,
          "minimum": 1,
          "maximum": 500
        },
        "include": {
          "type": "string"
        },
        "filter": {
          "type": "string",
          "description": "A function that must evaluate to true for a subscription to be returned. (OData-style expression passed as $filter)"
        },
        "orderBy": {
          "type": "string",
          "description": "Determines what values are used to order a collection of subscription. (OData-style expression passed as $orderBy)"
        }
      }
    },
    "annotations": {
      "title": "Retrieves the subscriptions.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "subscriptions_get_subscription",
    "description": "Retrieves a specific subscription based on the given ID.\n[GET /api/subscriptions/{subscriptionId}]",
    "method": "GET",
    "path": "/api/subscriptions/{subscriptionId}",
    "pathParams": [
      {
        "arg": "subscriptionId",
        "name": "subscriptionId"
      }
    ],
    "queryParams": [
      {
        "arg": "include",
        "name": "include"
      }
    ],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "subscriptionId": {
          "type": "string",
          "description": "The subscription ID.",
          "format": "uuid"
        },
        "include": {
          "type": "string"
        }
      },
      "required": [
        "subscriptionId"
      ]
    },
    "annotations": {
      "title": "Retrieves a specific subscription based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "subscriptions_get_addons",
    "description": "Retrieves the addons of a specific subscription based on the given ID.\n[GET /api/subscriptions/{subscriptionId}/addons]",
    "method": "GET",
    "path": "/api/subscriptions/{subscriptionId}/addons",
    "pathParams": [
      {
        "arg": "subscriptionId",
        "name": "subscriptionId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "subscriptionId": {
          "type": "string",
          "description": "The subscription ID.",
          "format": "uuid"
        }
      },
      "required": [
        "subscriptionId"
      ]
    },
    "annotations": {
      "title": "Retrieves the addons of a specific subscription based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "subscriptions_cancel_addon_end_of_billing_period",
    "description": "Cancels an addon at the end of the billing period.\n[POST /api/subscriptions/{subscriptionId}/addons/{addonId}/cancelendofbillingperiod] WRITE (destructive).",
    "method": "POST",
    "path": "/api/subscriptions/{subscriptionId}/addons/{addonId}/cancelendofbillingperiod",
    "pathParams": [
      {
        "arg": "subscriptionId",
        "name": "subscriptionId"
      },
      {
        "arg": "addonId",
        "name": "addonId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "subscriptionId": {
          "type": "string",
          "description": "The subscription ID.",
          "format": "uuid"
        },
        "addonId": {
          "type": "string",
          "description": "The addon ID.",
          "format": "uuid"
        }
      },
      "required": [
        "subscriptionId",
        "addonId"
      ]
    },
    "annotations": {
      "title": "Cancels an addon at the end of the billing period.",
      "readOnlyHint": false,
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "name": "subscriptions_get",
    "description": "Retrieves the custom fields of a specific subscription based on the given ID.\n[GET /api/subscriptions/{subscriptionId}/customfields]",
    "method": "GET",
    "path": "/api/subscriptions/{subscriptionId}/customfields",
    "pathParams": [
      {
        "arg": "subscriptionId",
        "name": "subscriptionId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "subscriptionId": {
          "type": "string",
          "description": "The subscription ID.",
          "format": "uuid"
        }
      },
      "required": [
        "subscriptionId"
      ]
    },
    "annotations": {
      "title": "Retrieves the custom fields of a specific subscription based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "subscriptions_get_characteristics",
    "description": "Retrieves the characteristics of a specific subscription based on the given ID.\n[GET /api/subscriptions/{subscriptionId}/characteristics]",
    "method": "GET",
    "path": "/api/subscriptions/{subscriptionId}/characteristics",
    "pathParams": [
      {
        "arg": "subscriptionId",
        "name": "subscriptionId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "subscriptionId": {
          "type": "string",
          "description": "The subscription ID.",
          "format": "uuid"
        }
      },
      "required": [
        "subscriptionId"
      ]
    },
    "annotations": {
      "title": "Retrieves the characteristics of a specific subscription based on the given ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "subscriptions_get_current_installment_plan",
    "description": "Subscriptions_GetCurrentInstallmentPlan\n[GET /api/subscriptions/{subscriptionId}/currentInstallmentplan]",
    "method": "GET",
    "path": "/api/subscriptions/{subscriptionId}/currentInstallmentplan",
    "pathParams": [
      {
        "arg": "subscriptionId",
        "name": "subscriptionId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "subscriptionId": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "subscriptionId"
      ]
    },
    "annotations": {
      "title": "Subscriptions_GetCurrentInstallmentPlan",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "subscriptions_cancel",
    "description": "Cancels a subscription.\n[POST /api/subscriptions/{subscriptionId}/cancel] WRITE (destructive).",
    "method": "POST",
    "path": "/api/subscriptions/{subscriptionId}/cancel",
    "pathParams": [
      {
        "arg": "subscriptionId",
        "name": "subscriptionId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "subscriptionId": {
          "type": "string",
          "description": "The subscription ID.",
          "format": "uuid"
        }
      },
      "required": [
        "subscriptionId"
      ]
    },
    "annotations": {
      "title": "Cancels a subscription.",
      "readOnlyHint": false,
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "name": "subscriptions_update_subscription_quantity",
    "description": "Change the quantity of a specific subscription based on the given ID at a specific date.\n[POST /api/subscriptions/{subscriptionId}/quantity] WRITE.",
    "method": "POST",
    "path": "/api/subscriptions/{subscriptionId}/quantity",
    "pathParams": [
      {
        "arg": "subscriptionId",
        "name": "subscriptionId"
      }
    ],
    "queryParams": [],
    "hasBody": true,
    "inputSchema": {
      "type": "object",
      "properties": {
        "subscriptionId": {
          "type": "string",
          "description": "The subscription ID.",
          "format": "uuid"
        },
        "body": {
          "type": "object",
          "properties": {
            "quantity": {
              "type": "integer"
            }
          },
          "required": [
            "quantity",
            "effectiveDate"
          ],
          "description": "Contains the new quantity and effective date values of the subscription."
        }
      },
      "required": [
        "subscriptionId",
        "body"
      ]
    },
    "annotations": {
      "title": "Change the quantity of a specific subscription based on the given ID at a specific date.",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "name": "subscriptions_get_quantity_request_by_id",
    "description": "Retrieves the UpdateSubscriptionQuantityRequest of a specific subscription based on the given subscription ID and Request ID.\n[GET /api/subscriptions/{subscriptionId}/quantityrequest/{requestId}]",
    "method": "GET",
    "path": "/api/subscriptions/{subscriptionId}/quantityrequest/{requestId}",
    "pathParams": [
      {
        "arg": "subscriptionId",
        "name": "subscriptionId"
      },
      {
        "arg": "requestId",
        "name": "requestId"
      }
    ],
    "queryParams": [],
    "hasBody": false,
    "inputSchema": {
      "type": "object",
      "properties": {
        "subscriptionId": {
          "type": "string",
          "description": "The subscription ID.",
          "format": "uuid"
        },
        "requestId": {
          "type": "string",
          "description": "Contains the requestId of needed UpdateSubscriptionQuantityRequest",
          "format": "uuid"
        }
      },
      "required": [
        "subscriptionId",
        "requestId"
      ]
    },
    "annotations": {
      "title": "Retrieves the UpdateSubscriptionQuantityRequest of a specific subscription based on the given subscription ID and Request ID.",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "name": "subscriptions_set_autorenewal",
    "description": "Updates the auto renewal of a specific subscription based on the given ID.\n[POST /api/subscriptions/{subscriptionId}/autoRenewalSettings] WRITE.",
    "method": "POST",
    "path": "/api/subscriptions/{subscriptionId}/autoRenewalSettings",
    "pathParams": [
      {
        "arg": "subscriptionId",
        "name": "subscriptionId"
      }
    ],
    "queryParams": [],
    "hasBody": true,
    "inputSchema": {
      "type": "object",
      "properties": {
        "subscriptionId": {
          "type": "string",
          "description": "The subscription ID.",
          "format": "uuid"
        },
        "body": {
          "type": "object",
          "properties": {
            "autoRenewalEnabled": {
              "type": "boolean"
            }
          },
          "required": [
            "autoRenewalEnabled"
          ],
          "description": "The desired value to set to the auto renewal field."
        }
      },
      "required": [
        "subscriptionId",
        "body"
      ]
    },
    "annotations": {
      "title": "Updates the auto renewal of a specific subscription based on the given ID.",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  }
];
